// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtvXcpjFMv_ieUgTX5OxJ3NnKbw2yX5kA',
    appId: '1:640909574959:web:df1991534ce395b7ab57da',
    messagingSenderId: '640909574959',
    projectId: 'essex-smart-ac',
    authDomain: 'essex-smart-ac.firebaseapp.com',
    storageBucket: 'essex-smart-ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvCyTb5dM0P9Y0OgrfrYKeubuo1td-0xI',
    appId: '1:640909574959:android:bdd201beb26364b1ab57da',
    messagingSenderId: '640909574959',
    projectId: 'essex-smart-ac',
    storageBucket: 'essex-smart-ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGzSxhdfJ1aCJ0ydUqQVMAohxy1FEIM0w',
    appId: '1:640909574959:ios:a6ef6e7e0b67fef9ab57da',
    messagingSenderId: '640909574959',
    projectId: 'essex-smart-ac',
    storageBucket: 'essex-smart-ac.firebasestorage.app',
    iosBundleId: 'ai.smart.ac',
  );
}
