###
### iOS Fastlane Configuration
###

import("../../fastlane/Fastfile")
require 'plist'

def api_key_connection
  UI.message("🔑 Generating App Store Connect API key")
  app_store_connect_api_key(
    key_id:               ENV["ASC_KEY_ID"],
    issuer_id:            ENV["ASC_ISSUER_ID"],
    key_content:          ENV["ASC_PRIVATE_KEY"],
    is_key_content_base64: true,
    duration:             1200,
    in_house:             false
  )
end

def setup_code_signing(api_key)
  UI.message("🔒 Setting up code signing")
  cocoapods(clean_install: is_ci)

  # run match and capture the path to the downloaded provisioning profile
  profile_path = match(
    type:            'appstore',
    api_key:         api_key,
    verbose:         true,
    readonly:        is_ci,
    app_identifier:  ENV['BUNDLE_ID']
  )

  UI.success("✅ match returned provisioning profile:")
  UI.message("   • Bundle ID: #{ENV['BUNDLE_ID']}")
  UI.message("   • Profile:   #{profile_path}")

  return profile_path
end

def build_and_upload(options, env)
  UI.header("🚀 Fastlane starting build_and_upload (#{env})")
  UI.message("🔎 ENV['BUNDLE_ID'] = #{ENV['BUNDLE_ID'].inspect}")

  version      = options[:app_version]
  build_number = options[:build_number]
  UI.message("📦 Build parameters: version=#{version}, build_number=#{build_number}")

  increment_version_number(version_number: version)
  increment_build_number(build_number: build_number)
  setup_ci if is_ci

  api_key      = api_key_connection
  profile_path = setup_code_signing(api_key)

  scheme_name = 'Runner'
  build_dir   = "./build/#{env.to_s.capitalize}"

  UI.message("📝 Scheme: #{scheme_name}")
  UI.message("📂 Build directory: #{build_dir}")

  archive_configuration = "Release"
  UI.message("⚙️ Archive configuration: #{archive_configuration}")

  archive_path = "#{build_dir}.xcarchive"

  build_app(
    clean:            true,
    scheme:           scheme_name,
    workspace:        "Runner.xcworkspace",
    configuration:    archive_configuration,
    export_method:    "app-store",
    archive_path:     archive_path,
    output_directory: build_dir,
    export_options: {
      provisioningProfiles: {
        ENV['BUNDLE_ID'] => "match AppStore #{ENV['BUNDLE_ID']}"
      }
    }
  )

  pilot(
    api_key:                         api_key,
    ipa:                             "#{build_dir}/Runner.ipa",
    team_id:                         ENV["TEAM_ID"],
    itc_provider:                    ENV["TEAM_ID"],
    skip_waiting_for_build_processing: true,
    distribute_external:            true,
#     groups:                         ["ExternalSmartAc"],
    changelog:                      ""
  )
end

platform :ios do
  desc "Build & Upload to TestFlight"
  lane :staging do |options|
    UI.header("🏷 Running staging lane")
    build_and_upload(options, :staging)
  end
end
