name: Test Cases

on:
  pull_request:
    branches-ignore:
      - master

  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.8'
          channel: 'stable'
          cache: true

      - name: Flutter pub get
        run: make get

      - name: Generate code
        run: make gen

      - name: Run test cases
        run: make test